[package]
name = "timewarrior-rs"
version = "1.4.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
anyhow = "1.0"
home = "0.5"
regex = "1"
nom = "7.1"